language: c++


addons:
  apt:
    packages:
      - cmake
      - yaml-cpp
      - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

before_install:

install:

before_script:

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./parser-test

after_success: