language: cpp
sudo: required
dist: trusty

env:
  global:
    - BUILD_CMD='make VERBOSE=1'
    - TEST_CMD='ctest -T test --output-on-failure -V'
    - OMP_NUM_THREADS=4
    - MPI_CONFIG='CMAKE_CMD_EXTRA="-DMPIEXEC:FILEPATH=$(which mpirun) -DMPIEXEC_MAX_NUMPROCS=${MPI_PROCS}"'

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
  apt:
    sources: &basic_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages: &native_deps
      - g++-7
      - clang-5.0
      - libtiff5-dev # version 5 ?
      - libgomp1 # version 4.8.4-2
      - libfftw3-dev # version 3.3.3

cache:
  directories:
    $HOME/cfitsio/

jobs:
  include:
    - stage: prepare cache
      script: mkdir -p ~/cfitsio; cd ~/cfitsio; curl -L -O http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3450.tar.gz

matrix:
  fast_finish: true

  include:
    - os: osx
      osx_image: xcode8
      env:
        - TITLE="Who knows - GCC"
        - MPI=OFF
        - openMP=OFF

    - os: osx
      osx_image: xcode8
      env:
        - TITLE="Who knows - GCC - OMP"
        - MPI=OFF
        - openMP=ON

    - os: osx
      osx_image: xcode8
      env:
        - TITLE="Who knows - GCC - MPI"
        - MPI=ON
        - openMP=ON
        - MPI_PROCS=2

    - os: osx
      osx_image: xcode8
      env:
        - TITLE="Who knows - Clang"
        - MPI=OFF
        - openMP=OFF

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - &all_deps [ libboost-all-dev, libeigen3-dev, libyaml-cpp-dev ]
            # libboost-all-dev version 1.54; libeigen3-dev version 3.2.0
            # libcfitsio3-dev version 3.34; libyaml-cpp-dev version 0.5.1
            #   \-> We need CFITSIO 3.41, this could help to install other dependencies...
      env:
        - TITLE="All dependencies - GCC"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=OFF
        - openMP=OFF

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - *all_deps
      env:
        - TITLE="All dependencies - GCC - OMP"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=OFF
        - openMP=ON

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - *all_deps
            - openmpi-bin # Version 1.6.5-8
            - libopenmpi-dev
      env:
        - TITLE="All dependencies - GCC - MPI"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=ON
        - openMP=ON
        - MPI_PROCS=4

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - *all_deps
            - mpich # version 3.0.4-6
      env:
        - TITLE="All dependencies - GCC - MPI - mpich"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=ON
        - openMP=ON
        - MPI_PROCS=4

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - *all_deps
      env:
        - TITLE="All dependencies - Clang"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=OFF
        - openMP=OFF

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - openmpi-bin # Version 1.6.5-8
            - libopenmpi-dev
      env:
        - TITLE="No dependencies - GCC - MPI"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - MPI=ON
        - openMP=ON
        - MPI_PROCS=4

    - os: linux
      addons:
        apt:
          sources:
            - *basic_sources
          packages:
            - *native_deps
            - *all_deps
            - doxygen # version 1.8.6-2
            - graphviz # version 2.36.0
      env:
        - TITLE="Documentation - GCC"
        - DEBUG=True
        - LDFLAGS='-pthread'
        - Tests=OFF
        - MPI=OFF
        - openMP=OFF
        - DOCS=ON
        - BUILD_CMD='make doc VERBOSE=1'
        - TEST_CMD=''

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build/cpp/docs/html
  target-branch: website # FIXME: Default gh-pages, set this for now to have both.
  verbose: true # FIXME: just at first to see logs
  on:
    branch: development
    condition: $TITLE = "Documentation - GCC"

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install gcc@7 fftw open-mpi yaml-cpp; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then ClangVer="-5.0"; fi
  - if [[ ${TITLE} = *GCC* ]]; then CC=gcc-7; else CC=clang${ClangVer}; fi
  - if [[ ${TITLE} = *GCC* ]]; then CXX=g++-7; else CXX=clang++${ClangVer}; fi
  # As MPI is not installed already, this variable is not set properly; this
  # way is set up for all the jobs in the same manner.
  - if [[ $MPI = ON ]]; then eval $MPI_CONFIG; fi
  - echo "==================== ${TITLE} ====================="

install:

before_script:

script:
  - pwd
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_BUILD_TYPE=Release \
    -Dtests=${Tests-ON} \
    -Ddompi=${MPI} \
    -Dexamples=OFF \
    -Dopenmp=${openMP} \
    -Ddocs=${DOCS-OFF} \
    -Dbenchmarks=${Benchmarks-OFF} \
    -DSopt_GIT_REPOSITORY=https://github.com/astro-informatics/sopt.git \
    -DSopt_GIT_TAG=development \
    -DCFitsIO_URL=${HOME}/cfitsio/cfitsio3410.tar.gz \
    ${CMAKE_CMD_EXTRA}
  - while sleep 540 ; do echo "=========== make is taking more than 9m - pinging travis =========="; done & # cfits may take long to download
  - eval $BUILD_CMD
  - if [ -z $DOCS ]; then tail -n +1 /home/travis/build/astro-informatics/purify/build/external/src/Lookup-CFitsIO-stamp/Lookup-CFitsIO-*.log; fi
  - eval $TEST_CMD

after_success:

