language: c++


addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libyaml-cpp0.6.0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

before_install:

install:

before_script:

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./parser-test

after_success: